export const SET_SELECTED_TAB = 'SET_SELECTED_TAB'

export const FETCH_POST_LIST = 'FETCH_POST_LIST'
export const FRESH_POST_START = 'FRESH_POST_START'
export const FRESH_POST_FINISH = 'FRESH_POST_FINISH'
export const FETCH_NEXT_PAGE_START = 'FETCH_NEXT_PAGE_START'
export const FETCH_NEXT_PAGE_FINISH = 'FETCH_NEXT_PAGE_FINISH'
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL'


export const SCENE_CHANGE = 'SCENE_CHANGE'